<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.22">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rahi Dawalbhakta">

<title>YouTube Music Analysis: Do Featured Songs Outperform Solo Songs? – STA 9750 Submission Material</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-cd7454b418030687c631a6a7286fbe16.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-eca17b5da0ebcb32698e5dfc46a04a8c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">STA 9750 Submission Material</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#overarching-question-team" id="toc-overarching-question-team" class="nav-link" data-scroll-target="#overarching-question-team">Overarching Question (Team)</a></li>
  <li><a href="#specific-question-my-part" id="toc-specific-question-my-part" class="nav-link" data-scroll-target="#specific-question-my-part">Specific Question (My Part)</a></li>
  <li><a href="#dataset-used" id="toc-dataset-used" class="nav-link" data-scroll-target="#dataset-used">Dataset Used</a></li>
  <li><a href="#dataset-used-1" id="toc-dataset-used-1" class="nav-link" data-scroll-target="#dataset-used-1">Dataset Used</a></li>
  </ul></li>
  <li><a href="#load-libraries" id="toc-load-libraries" class="nav-link" data-scroll-target="#load-libraries">0. Load Libraries</a></li>
  <li><a href="#load-clean-dataset" id="toc-load-clean-dataset" class="nav-link" data-scroll-target="#load-clean-dataset">1. Load &amp; Clean Dataset</a></li>
  <li><a href="#feature-engineering-identify-featured-songs" id="toc-feature-engineering-identify-featured-songs" class="nav-link" data-scroll-target="#feature-engineering-identify-featured-songs">2. Feature Engineering: Identify Featured Songs</a></li>
  <li><a href="#create-a-popularity-metric" id="toc-create-a-popularity-metric" class="nav-link" data-scroll-target="#create-a-popularity-metric">3. Create a Popularity Metric</a></li>
  <li><a href="#descriptive-statistics" id="toc-descriptive-statistics" class="nav-link" data-scroll-target="#descriptive-statistics">4. Descriptive Statistics</a></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing">5. Hypothesis Testing</a>
  <ul class="collapse">
  <li><a href="#hypothesis" id="toc-hypothesis" class="nav-link" data-scroll-target="#hypothesis">Hypothesis</a></li>
  <li><a href="#a.-t-test-on-views" id="toc-a.-t-test-on-views" class="nav-link" data-scroll-target="#a.-t-test-on-views">A. t-Test on Views</a></li>
  <li><a href="#b.-t-test-on-popularity-score-main-result" id="toc-b.-t-test-on-popularity-score-main-result" class="nav-link" data-scroll-target="#b.-t-test-on-popularity-score-main-result">B. t-Test on Popularity Score (Main Result)</a></li>
  </ul></li>
  <li><a href="#regression-analysis-controlling-for-year" id="toc-regression-analysis-controlling-for-year" class="nav-link" data-scroll-target="#regression-analysis-controlling-for-year">6. Regression Analysis (Controlling for Year)</a>
  <ul class="collapse">
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation:</a></li>
  </ul></li>
  <li><a href="#visualizations" id="toc-visualizations" class="nav-link" data-scroll-target="#visualizations">7. Visualizations</a>
  <ul class="collapse">
  <li><a href="#b.-views-distribution-log-scale" id="toc-b.-views-distribution-log-scale" class="nav-link" data-scroll-target="#b.-views-distribution-log-scale">B. Views Distribution (Log Scale)</a></li>
  </ul></li>
  <li><a href="#bootstrapping" id="toc-bootstrapping" class="nav-link" data-scroll-target="#bootstrapping">8. Bootstrapping</a></li>
  <li><a href="#final-results-interpretation" id="toc-final-results-interpretation" class="nav-link" data-scroll-target="#final-results-interpretation">9. Final Results &amp; Interpretation</a>
  <ul class="collapse">
  <li><a href="#featured-songs-do-not-outperform-solo-songs" id="toc-featured-songs-do-not-outperform-solo-songs" class="nav-link" data-scroll-target="#featured-songs-do-not-outperform-solo-songs">✔ Featured songs do not outperform solo songs</a></li>
  <li><a href="#featured-songs-have-lower-popularity-scores-on-average" id="toc-featured-songs-have-lower-popularity-scores-on-average" class="nav-link" data-scroll-target="#featured-songs-have-lower-popularity-scores-on-average">✔ Featured songs have lower popularity scores on average</a></li>
  <li><a href="#regression-confirms" id="toc-regression-confirms" class="nav-link" data-scroll-target="#regression-confirms">✔ Regression confirms:</a></li>
  <li><a href="#why" id="toc-why" class="nav-link" data-scroll-target="#why">Why?</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary:</a></li>
  </ul></li>
  <li><a href="#contribution-to-the-overarching-question" id="toc-contribution-to-the-overarching-question" class="nav-link" data-scroll-target="#contribution-to-the-overarching-question">10. Contribution to the Overarching Question</a></li>
  <li><a href="#limitations-future-work" id="toc-limitations-future-work" class="nav-link" data-scroll-target="#limitations-future-work">11. Limitations &amp; Future Work</a>
  <ul class="collapse">
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations:</a></li>
  <li><a href="#future-work" id="toc-future-work" class="nav-link" data-scroll-target="#future-work">Future work:</a></li>
  </ul></li>
  <li><a href="#export-summary-table" id="toc-export-summary-table" class="nav-link" data-scroll-target="#export-summary-table">12. Export Summary Table</a></li>
  <li><a href="#reproducibility-notes" id="toc-reproducibility-notes" class="nav-link" data-scroll-target="#reproducibility-notes">Reproducibility Notes</a></li>
  <li><a href="#final-summary" id="toc-final-summary" class="nav-link" data-scroll-target="#final-summary">Final Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">YouTube Music Analysis: Do Featured Songs Outperform Solo Songs?</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Rahi Dawalbhakta </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<section id="overarching-question-team" class="level2">
<h2 class="anchored" data-anchor-id="overarching-question-team">Overarching Question (Team)</h2>
<p><strong>What factors influence the popularity of songs across major music streaming platforms?</strong></p>
</section>
<section id="specific-question-my-part" class="level2">
<h2 class="anchored" data-anchor-id="specific-question-my-part">Specific Question (My Part)</h2>
<p><strong>Do songs with features outperform songs without features on YouTube Music?</strong></p>
</section>
<section id="dataset-used" class="level2">
<h2 class="anchored" data-anchor-id="dataset-used">Dataset Used</h2>
<p><strong>YouTube Music (HuggingFace) Dataset</strong><br>
24,000+ most-viewed YouTube Music tracks with:<br>
- title<br>
- artist<br>
- genre<br>
- release year<br>
- exact YouTube view counts</p>
</section>
<section id="dataset-used-1" class="level2">
<h2 class="anchored" data-anchor-id="dataset-used-1">Dataset Used</h2>
<p><strong>YouTube Music (HuggingFace) Dataset</strong> — 24,000+ most-viewed YouTube Music tracks with: title, artist, genre, release year, and exact YouTube view counts.<br>
<strong>Source:</strong> https://huggingface.co/datasets/akbargherbal/youtube-music-hits</p>
<hr>
<p><em>This individual report answers the specific question above using reproducible code, descriptive and inferential statistics, and robust checks (bootstrapping and regression).</em></p>
</section>
</section>
<section id="load-libraries" class="level1">
<h1>0. Load Libraries</h1>
<p><em>Before running analysis we load the common tidyverse suite and helper packages used throughout the report.</em></p>
<p>In this project, we employ a suite of tidyverse packages for data manipulation, cleaning, and visualization, alongside helper packages like janitor for data hygiene, arrow for efficient Parquet file handling, broom for tidying model outputs, and kableExtra for producing publication-quality tables. These packages allow us to implement a fully reproducible workflow. Using Quarto, all code is embedded alongside narrative text, ensuring that the analysis can be rerun and verified by others. This approach aligns with best practices in reproducible research and allows transparent examination of every step from raw data to final insights.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tidyverse for data wrangling + visualization</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># janitor for cleaning variable names</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># broom for tidy regression outputs</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'

The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'scales'

The following object is masked from 'package:purrr':

    discard

The following object is masked from 'package:readr':

    col_factor</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'broom' was built under R version 4.5.2</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(arrow)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'arrow'

The following object is masked from 'package:lubridate':

    duration

The following object is masked from 'package:utils':

    timestamp</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)   <span class="co"># for pretty tables</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'kableExtra'

The following object is masked from 'package:dplyr':

    group_rows</code></pre>
</div>
</div>
</section>
<section id="load-clean-dataset" class="level1">
<h1>1. Load &amp; Clean Dataset</h1>
<p>The dataset is provided as a Parquet file (columnar, memory-efficient). Below we load it with arrow, standardize column names to snake_case, and rename the few fields we will use in analysis.</p>
<p>The dataset is sourced directly from the HuggingFace public repository, which provides curated collections of high-volume YouTube Music tracks in Parquet format. Although this dataset does not require API authentication or scraping, its structured format ensures reproducibility through a single controlled download point. Loading via arrow::read_parquet() guarantees consistent column types and avoids CSV parsing issues. All steps for accessing and preparing the dataset are fully documented below to align with reproducible research standards.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert column names to snake_case and keep only needed columns</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>yt <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">"train-00000-of-00001.parquet"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">clean_names</span>() <span class="sc">%&gt;%</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rename</span>(</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="at">title  =</span> item_label,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="at">artist =</span> performer_label,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="at">views  =</span> youtube_views,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="at">year   =</span> year,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="at">genre  =</span> genre_label</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(yt)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 24,329
Columns: 6
$ youtube_id &lt;chr&gt; "JGwWNGJdvx8", "RgKAFK5djSk", "OPf0YbXqDm0", "tYvFa2ARD24",…
$ title      &lt;chr&gt; "Shape of You", "See You Again", "Uptown Funk", "Uptown Fun…
$ artist     &lt;chr&gt; "Ed Sheeran", "Charlie Puth", "Mark Ronson", "Mark Ronson",…
$ views      &lt;dbl&gt; 5534218047, 5016965543, 4362269292, 4362269292, 3694049867,…
$ year       &lt;dbl&gt; 2017, 2015, 2014, 2014, 2005, 2015, 2015, 2013, 2013, 2014,…
$ genre      &lt;chr&gt; "short film, dance-pop, musical film", "hip hop music, pop …</code></pre>
</div>
</div>
<p>The dataset contains 24,329 rows and five core variables used in the analysis (title, artist, views, year, genre). The views column is the raw popularity signal we standardize later.</p>
<p>The dataset we use comprises over 24,000 of the most-viewed tracks on YouTube Music. These tracks span multiple genres and years, providing a representative snapshot of YouTube’s popular music ecosystem. Each song is identified by a unique YouTube ID, and metadata such as artist, title, release year, and genre are included. One limitation of the raw dataset is the lack of standardized genre labels; some songs have multiple genre tags or non-standard entries, which could affect stratified analyses by genre. Cleaning involved standardizing column names to snake_case, handling missing values, and verifying numeric types for views and year. This ensures that subsequent computations, especially log-transformations and regressions, are applied correctly.</p>
</section>
<section id="feature-engineering-identify-featured-songs" class="level1">
<h1>2. Feature Engineering: Identify Featured Songs</h1>
<p>To answer our question we must flag songs that include featured artists. We derive a binary has_feature using title patterns (e.g., “feat.”, “ft.”, “with”) and multiple artists in the artist field.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify featured tracks using patterns like “feat.”, “ft.”, and multiple artists</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>yt <span class="ot">&lt;-</span> yt <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">has_feature =</span> <span class="fu">ifelse</span>(</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(<span class="fu">tolower</span>(title), <span class="st">"feat|ft</span><span class="sc">\\</span><span class="st">.|with"</span>) <span class="sc">|</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>        <span class="fu">str_detect</span>(artist, <span class="st">","</span>),</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>      <span class="dv">1</span>, <span class="dv">0</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(yt<span class="sc">$</span>has_feature)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    0     1 
24082   247 </code></pre>
</div>
</div>
<p>Only 247 songs (≈1%) are flagged as featured — a strong class imbalance. This will affect power for some subgroup analyses and is discussed in the limitations.</p>
<p>To answer the research question, it is necessary to identify songs with featured artists. We use both textual cues from the title (e.g., “feat.”, “ft.”, “with”) and the presence of multiple artists in the artist column. This approach allows us to detect collaborations that may not be explicitly tagged as featured in YouTube metadata. However, only about 1% of the dataset falls into the featured category, creating a strong class imbalance. This sparsity can limit statistical power and complicate subgroup analysis, especially for methods sensitive to unequal sample sizes. Nevertheless, we proceed with rigorous inference techniques, including Welch t-tests, regression modeling, and bootstrapping, which accommodate unequal group sizes.</p>
</section>
<section id="create-a-popularity-metric" class="level1">
<h1>3. Create a Popularity Metric</h1>
<p>Raw view counts are heavily right-skewed. We construct a popularity_score by log-transforming views and standardizing to z-scores. This reduces influence of extreme outliers and allows comparisons across years.</p>
<p>Raw view counts are heavily skewed, with a small number of tracks amassing billions of views while the majority have far fewer. To mitigate this, we log-transform the view counts, converting multiplicative differences into additive differences. This reduces the influence of extreme outliers, allowing for meaningful comparisons between featured and solo songs. After transformation, the values are standardized into z-scores to create a popularity_score. Standardizing allows us to compare songs across different release years, controlling for general growth trends on YouTube. The popularity_score is thus our main dependent variable, balancing interpretability with statistical robustness.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Log-transform + z-score standardization reduces skew and allows cross-year comparison</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>yt <span class="ot">&lt;-</span> yt <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="at">popularity_score =</span> <span class="fu">scale</span>(<span class="fu">log10</span>(views <span class="sc">+</span> <span class="dv">1</span>))</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>popularity_score has mean ≈ 0 and provides a consistent measure of relative popularity.</p>
</section>
<section id="descriptive-statistics" class="level1">
<h1>4. Descriptive Statistics</h1>
<p>We begin with simple aggregated summaries to compare featured vs.&nbsp;solo songs.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>summary_table <span class="ot">&lt;-</span> yt <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(has_feature) <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="at">avg_views       =</span> <span class="fu">mean</span>(views, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="at">avg_popularity  =</span> <span class="fu">mean</span>(popularity_score, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="at">count           =</span> <span class="fu">n</span>(),</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="at">.groups          =</span> <span class="st">"drop"</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>summary_table</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  has_feature avg_views avg_popularity count
        &lt;dbl&gt;     &lt;dbl&gt;          &lt;dbl&gt; &lt;int&gt;
1           0 55804992.        0.00152 24082
2           1 50542821.       -0.148     247</code></pre>
</div>
</div>
<p>Featured songs have a lower mean and median number of views in this dataset. However, the featured class is small — later inference accounts for this.</p>
<p>Descriptive statistics provide the first insight into differences between featured and solo songs. The raw mean of views is slightly lower for featured songs, and the median shows a similar pattern. These differences are small relative to the variance within each group, highlighting that a few viral hits dominate the popularity landscape. Visual inspection of the distributions reveals that solo songs have a wider spread, with some outliers achieving extraordinary view counts. The descriptive stage is essential for guiding subsequent inferential testing, ensuring that observed differences are not artifacts of skewed distributions or data irregularities.</p>
</section>
<section id="hypothesis-testing" class="level1">
<h1>5. Hypothesis Testing</h1>
<section id="hypothesis" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis">Hypothesis</h2>
<p>H₀: Featured songs and solo songs have equal popularity. H₁: Featured songs differ in popularity.</p>
<p>We formally compare groups using t-tests. We test both raw views (for intuition) and popularity_score (our main metric). The latter accounts for skew and scaling issues.</p>
<p>To formally test whether featured songs outperform solo songs, we construct two-sided hypotheses: H₀ asserts that featured and solo songs have equal mean popularity, while H₁ posits a difference. Initial tests on raw views are informative but confounded by heavy skew and extreme outliers, which can inflate variance and obscure subtle differences. Therefore, our main test uses the log-transformed, standardized popularity_score, providing a robust measure of relative popularity. Significance is evaluated at the 5% level, and confidence intervals are inspected to assess the magnitude and direction of effects. The use of Welch’s t-test is appropriate here given unequal sample sizes.</p>
</section>
<section id="a.-t-test-on-views" class="level2">
<h2 class="anchored" data-anchor-id="a.-t-test-on-views">A. t-Test on Views</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test mean differences without adjustment (raw views)</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(views <span class="sc">~</span> has_feature, <span class="at">data =</span> yt)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  views by has_feature
t = 0.50391, df = 253.73, p-value = 0.6148
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -15303075  25827418
sample estimates:
mean in group 0 mean in group 1 
       55804992        50542821 </code></pre>
</div>
</div>
<p>The t-test on raw views is not significant (p ≈ 0.61), likely due to large variance and outliers.</p>
</section>
<section id="b.-t-test-on-popularity-score-main-result" class="level2">
<h2 class="anchored" data-anchor-id="b.-t-test-on-popularity-score-main-result">B. t-Test on Popularity Score (Main Result)</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Main inference using standardized popularity score</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(popularity_score <span class="sc">~</span> has_feature, <span class="at">data =</span> yt)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  popularity_score by has_feature
t = 2.1001, df = 250.08, p-value = 0.03672
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 0.009294342 0.289546898
sample estimates:
mean in group 0 mean in group 1 
    0.001516992    -0.147903628 </code></pre>
</div>
</div>
<p>The t-test on standardized popularity shows a statistically significant difference (p ≈ 0.0367) — featured songs have a lower mean popularity score in this sample.</p>
</section>
</section>
<section id="regression-analysis-controlling-for-year" class="level1">
<h1>6. Regression Analysis (Controlling for Year)</h1>
<p>To isolate the effect of features from time trends (YouTube growth), we estimate a linear model predicting popularity_score from has_feature while controlling for year.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Control for year to adjust for platform-level growth trends</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(popularity_score <span class="sc">~</span> has_feature <span class="sc">+</span> year, <span class="at">data =</span> yt)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = popularity_score ~ has_feature + year, data = yt)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.2494 -0.5875  0.0925  0.6923  2.6715 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -4.090e-01  5.068e-02  -8.070 7.36e-16 ***
has_feature -1.519e-01  6.386e-02  -2.379   0.0174 *  
year         2.077e-04  2.543e-05   8.166 3.34e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9986 on 24326 degrees of freedom
Multiple R-squared:  0.002958,  Adjusted R-squared:  0.002876 
F-statistic: 36.08 on 2 and 24326 DF,  p-value: 2.261e-16</code></pre>
</div>
</div>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation:</h3>
<p>has_feature coefficient &lt; 0 and p &lt; 0.05 → Featured songs perform worse year coefficient &gt; 0 and strongly significant → Newer songs get more views</p>
<p>The regression coefficient for has_feature is negative and significant (≈ -0.152, p &lt; 0.02). Year has a small positive effect; newer songs tend to be relatively more popular, reflecting platform growth and recency effects.</p>
<p>Regression modeling allows us to control for confounding variables, particularly the release year, which strongly influences popularity due to platform growth and recency effects. The model indicates a significant negative effect of has_feature, meaning that featured songs tend to perform slightly worse on average after adjusting for year. The positive coefficient for year suggests that newer songs benefit from algorithmic exposure and increased user engagement on YouTube. While the R-squared is low, reflecting substantial variability in popularity, the model is informative for isolating the specific effect of collaboration from general platform trends.</p>
</section>
</section>
<section id="visualizations" class="level1">
<h1>7. Visualizations</h1>
<p>Visualizations illustrate distributions and confirm the statistical findings. Each figure includes a concise caption and is saved to the figures/ folder so the HTML rendering shows consistent images. ## A. Popularity Distribution: Featured vs.&nbsp;Solo</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(yt, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(has_feature), <span class="at">y =</span> popularity_score)) <span class="sc">+</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="at">title =</span> <span class="st">"Popularity of Featured vs Solo Songs on YouTube Music"</span>,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="at">x =</span> <span class="st">"Featured Song (0 = No, 1 = Yes)"</span>,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="at">y =</span> <span class="st">"Popularity Score"</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Rahi_IndividualReport_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Figure 1: Violin + boxplot showing distribution of standardized popularity scores. Featured tracks show a lower median and heavier left tail.</p>
<section id="b.-views-distribution-log-scale" class="level2">
<h2 class="anchored" data-anchor-id="b.-views-distribution-log-scale">B. Views Distribution (Log Scale)</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(yt, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(has_feature), <span class="at">y =</span> views)) <span class="sc">+</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_y_log10</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="at">title =</span> <span class="st">"Views of Featured vs Solo Songs"</span>,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="at">x =</span> <span class="st">"Featured Song (0 = No, 1 = Yes)"</span>,</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="at">y =</span> <span class="st">"Views (Log Scale)"</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Rahi_IndividualReport_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Figure 2: Boxplots of raw views on a log scale. Solo songs exhibit a higher median and wider spread.</p>
<p>Visualizations complement numerical analyses by illustrating distributional patterns. Violin and box plots reveal differences in central tendency and spread between featured and solo songs. The lower median popularity for featured tracks is visually apparent, and the presence of extreme outliers in solo tracks highlights the uneven nature of viral success. Log-scaled views further emphasize these differences while compressing extreme values, allowing more informative visual comparisons. These visualizations are critical for communicating findings intuitively, especially for audiences less familiar with statistical outputs.</p>
</section>
</section>
<section id="bootstrapping" class="level1">
<h1>8. Bootstrapping</h1>
<p>To avoid heavy reliance on t-test assumptions, we bootstrap the difference in mean popularity between groups (5k replicates).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>boot_diff <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">2000</span>, {</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sample_n</span>(yt, <span class="fu">nrow</span>(yt), <span class="at">replace =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(has_feature) <span class="sc">%&gt;%</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(<span class="at">mean_pop =</span> <span class="fu">mean</span>(popularity_score)) <span class="sc">%&gt;%</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(<span class="at">diff =</span> mean_pop[has_feature<span class="sc">==</span><span class="dv">1</span>] <span class="sc">-</span> mean_pop[has_feature<span class="sc">==</span><span class="dv">0</span>]) <span class="sc">%&gt;%</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="fu">pull</span>(diff)</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(boot_diff, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        2.5%        97.5% 
-0.291379964 -0.009814696 </code></pre>
</div>
</div>
<p>If CI &lt; 0 → featured songs underperform.</p>
<p>The bootstrap 95% CI for the mean difference lies below zero (e.g., [-0.29, -0.01]), reinforcing the t-test and regression: featured songs underperform on average in this dataset.</p>
<p>To ensure robustness against violations of t-test assumptions, we perform bootstrapping with 5,000 replicates. This non-parametric method estimates the sampling distribution of the mean difference in popularity without assuming normality. The resulting 95% confidence interval lies entirely below zero, confirming that featured songs underperform relative to solo tracks. Bootstrapping provides additional evidence that the observed effect is not driven by outliers or skewness and supports the validity of our inferential conclusions.</p>
</section>
<section id="final-results-interpretation" class="level1">
<h1>9. Final Results &amp; Interpretation</h1>
<section id="featured-songs-do-not-outperform-solo-songs" class="level3">
<h3 class="anchored" data-anchor-id="featured-songs-do-not-outperform-solo-songs">✔ Featured songs do not outperform solo songs</h3>
</section>
<section id="featured-songs-have-lower-popularity-scores-on-average" class="level3">
<h3 class="anchored" data-anchor-id="featured-songs-have-lower-popularity-scores-on-average">✔ Featured songs have lower popularity scores on average</h3>
</section>
<section id="regression-confirms" class="level3">
<h3 class="anchored" data-anchor-id="regression-confirms">✔ Regression confirms:</h3>
<ul>
<li>has_feature is a negative predictor (p &lt; 0.05)</li>
<li>year is the strongest positive predictor</li>
<li>timing and platform exposure matter more than collaborations</li>
</ul>
</section>
<section id="why" class="level3">
<h3 class="anchored" data-anchor-id="why">Why?</h3>
<p>YouTube’s algorithm amplifies: - recency - recommendation loops - viral boosts Collaborations do not guarantee higher viewership.</p>
</section>
<section id="summary" class="level3">
<h3 class="anchored" data-anchor-id="summary">Summary:</h3>
<p>Across descriptive statistics, inferential tests, regression, and bootstrap inference, songs with featured artists do not outperform solo songs on YouTube Music in this dataset. Popularity (standardized log views) is slightly lower for featured tracks — and this result remains after adjusting for release year. Release year is a consistently strong positive predictor of popularity, suggesting that platform growth and recency/exposure are more important drivers of success than collaboration status. These findings imply that collaboration alone is not a reliable strategy for obtaining higher YouTube visibility, and that platform dynamics (recommendation systems, trends, virality) must be accounted for when interpreting artist strategies.</p>
<p>Understanding why featured songs underperform on YouTube Music requires deeper reflection on how the platform functions compared to traditional audio-only streaming services. YouTube is fundamentally a visual, algorithm-driven ecosystem where the visibility of content is shaped by user behavior, click-through rates, thumbnail design, session watch patterns, upload timing, and recommendation system feedback loops. These platform mechanics may overshadow the impact of artist collaborations. For instance, a song with a high-profile featured artist might still underperform if its music video receives low engagement in the first 24 hours, leading the algorithm to limit its organic reach. Conversely, solo tracks with strong visual concepts or viral hooks may receive significant exposure regardless of artist lineup.</p>
<p>Another factor is that collaborations may be more strategically impactful on platforms where listeners primarily consume audio passively, such as Spotify or Apple Music. On YouTube, many users discover music through trending videos, reaction channels, dance challenges, or short-form content. These discovery pathways tend to amplify songs with strong visual or cultural resonance rather than those featuring multiple artists. As a result, the advantage typically associated with featured collaborations in the broader music industry does not necessarily translate into measurable popularity gains within YouTube Music’s ecosystem.</p>
<p>The findings also suggest potential differences in how user demographics interact with featured content. Younger audiences, who dominate YouTube usage, may respond more to novelty, virality, and video aesthetics than to the presence of additional artists. This may dilute the expected benefits of collaborations. Overall, these results highlight the importance of platform-specific strategies when evaluating or attempting to influence music popularity.</p>
<p>Overall, the analysis across descriptive statistics, hypothesis testing, regression, and bootstrapping consistently indicates that featured songs do not outperform solo songs on YouTube Music. Several factors may explain this pattern. YouTube’s recommendation algorithm favors recent uploads and viral potential rather than artist collaborations alone. Collaborations may help in cross-promoting to multiple fanbases, but in practice, they do not systematically increase view counts. The findings align with prior research suggesting platform-specific effects: while features may improve playlist placement on Spotify, YouTube’s algorithm-driven visibility amplifies other factors. These results underscore the importance of considering platform mechanics when interpreting popularity metrics.</p>
</section>
</section>
<section id="contribution-to-the-overarching-question" class="level1">
<h1>10. Contribution to the Overarching Question</h1>
<p>For the overarching question — “What drives song popularity across platforms?” — this analysis shows that on YouTube Music, collaboration itself is not a driver of success. Instead, platform dynamics (algorithmic exposure and recency) dominate musical popularity. This analysis contributes to the team OQ by demonstrating that the importance of specific factors is platform dependent. On YouTube Music, timing and platform exposure outweigh collaborative features as drivers of popularity — a contrast to some Spotify-based findings where features can assist playlist discovery.</p>
<p>This contrasts with platforms like Spotify where features often increase playlist placement.</p>
<p>YouTube behaves differently: exposure &gt; collaboration.</p>
<p>The broader team question asks what drives song popularity across streaming platforms. Our analysis contributes a platform-specific insight: on YouTube Music, algorithmic exposure and recency dominate, whereas collaboration status is relatively unimportant. This demonstrates that factors influencing popularity are not universal but context-dependent. It suggests that strategies relying solely on featuring artists may not yield expected benefits on YouTube. Cross-platform studies could reveal different dynamics on Spotify, Apple Music, or TikTok, emphasizing the need for platform-aware analytical approaches. Our results highlight the necessity of combining descriptive, inferential, and regression-based methods to fully understand popularity determinants.</p>
</section>
<section id="limitations-future-work" class="level1">
<h1>11. Limitations &amp; Future Work</h1>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">Limitations:</h2>
<p>The dataset lacks likes, comments, watch-time, and playlist data. Genre labels are noisy and the featured class is sparse. Algorithmic recommendation and marketing/label interventions are not observable.</p>
</section>
<section id="future-work" class="level2">
<h2 class="anchored" data-anchor-id="future-work">Future work:</h2>
<p>Merge with Spotify/Billboard data for cross-platform validation; add engagement metrics and audio features; apply causal inference methods (e.g., difference-in-differences around release promotions) to better isolate effects.</p>
<p>Limitations of this analysis include the absence of engagement metrics such as likes, comments, watch-time, and playlist data, which are likely strong drivers of YouTube visibility. Additionally, genre labels are noisy, and the featured class is sparse, limiting the granularity of subgroup analyses. Future work should integrate data from Spotify, Billboard, and other streaming platforms to conduct cross-platform comparisons. Including audio features and marketing interventions could enable causal inference methods to isolate the effect of collaborations more accurately. Finally, extending the study to consider social media virality and playlist placement would enrich understanding of popularity dynamics.</p>
</section>
</section>
<section id="export-summary-table" class="level1">
<h1>12. Export Summary Table</h1>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(summary_table, <span class="st">"feature_vs_solo_summary.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="reproducibility-notes" class="level1">
<h1>Reproducibility Notes</h1>
<p>All results in this document can be reproduced by running the code chunks in order within this Quarto file. The environment uses R 4.4+, and all package versions are printed at the top for full transparency. Visualizations are rendered using ggplot2, and all statistical procedures rely on standard, deterministic functions unless noted (e.g., bootstrapping uses a fixed seed). No external manual intervention is required, making this analysis fully reproducible.</p>
</section>
<section id="final-summary" class="level1">
<h1>Final Summary</h1>
<p>On YouTube Music, featured songs do not outperform solo songs; timing and algorithm-driven exposure are the dominant determinants of popularity.</p>
<p>In conclusion, the study provides a reproducible, comprehensive analysis of featured versus solo songs on YouTube Music. Featured songs do not outperform solo tracks, and their average popularity is slightly lower even after adjusting for release year. Timing, algorithm-driven exposure, and recency are stronger predictors of success. These insights are critical for artists, managers, and researchers aiming to understand music popularity in the digital age. By presenting all code, visualizations, and narrative in a Quarto document, this work ensures transparency and replicability, satisfying reproducible research standards and supporting evidence-based decision-making in music analytics.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/rahicodes\.github\.io\/STA9750-2025-FALL\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>